name = "rhel-golden-image"
description = "RHEL Golden Image"
version = "0.0.1"
modules = []
groups = []
distro = "REPLACEME-DISTRO"

[[packages]]
name = "bind-utils"

[[packages]]
name = "chrony"

[[packages]]
name = "lvm2"

[[packages]]
name = "wget"

[[packages]]
name = "git"

[[packages]]
name = "openssh-server"

[[packages]]
name = "bash-completion"

[[packages]]
name = "firewalld"

[[packages]]
name = "openscap-scanner"

[[packages]]
name = "openscap-utils"

[[packages]]
name = "scap-security-guide"

[[packages]]
name = "insights-client"

[[packages]]
name = "rhc"

[[packages]]
name = "rhc-worker-playbook"

[[packages]]
name = "glibc-langpack-en"

[[packages]]
name = "langpacks-en"

[[packages]]
name = "ansible-core"

[[packages]]
name = "rhel-system-roles"

[customizations]

[[customizations.user]]
name = "rexuser"
password = ""
key = ""
groups = ["wheel"]
uid = 5001

[customizations.timezone]
timezone = "Europe/Stockholm"
ntpservers = ["0.rhel.pool.ntp.org", "1.rhel.pool.ntp.org"]

[customizations.locale]
languages = ["en_US.UTF-8"]
keyboard = "sv-latin1"

[customizations.firewall]
[customizations.firewall.services]
enabled = ["cockpit", "ssh"]

[customizations.services]
enabled = ["cockpit.socket", "sshd.service"]

[[customizations.filesystem]]
mountpoint = "/home"
size = 1073741824

[[customizations.filesystem]]
mountpoint = "/tmp"
size = 1073741824

[[customizations.filesystem]]
mountpoint = "/"
size = 5368709120
